version: 2
updates:


  - package-ecosystem: "npm"
    directory: "/apps/core-api"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    groups:
      non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
